--
-- Database: `festivals`
--

-- --------------------------------------------------------

--
-- Table structure for table `festivals`
--

CREATE TABLE `festivals` (
  `id` int(11) NOT NULL,
  `title` varchar(64) NOT NULL,
  `description` text DEFAULT NULL,
  `location` varchar(256) NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `contact_name` varchar(64) NOT NULL,
  `contact_email` varchar(64) NOT NULL,
  `contact_phone` varchar(64) NOT NULL,
  `image_id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `festivals`
--

INSERT INTO `festivals` (`id`, `title`, `description`, `location`, `start_date`, `end_date`, `contact_name`, `contact_email`, `contact_phone`, `image_id`) VALUES
(1, 'Coachella', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisl enim, vitae placerat lorem dapibus ut. Ut lacinia ultrices convallis. Nam tristique sapien sed mollis mattis. Donec at facilisis lacus. Cras condimentum rhoncus sem lacinia congue. Nam egestas vulputate ipsum, viverra vehicula diam rutrum nec. Quisque commodo vehicula urna vel vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vehicula ex vel risus rutrum sodales. Sed consequat augue ac dui ornare, at aliquet lectus interdum. Nullam sed erat eget ex eleifend sagittis. Vestibulum tristique, neque et cursus blandit, nisi justo hendrerit diam, a condimentum dolor lacus ac elit.\r\n\r\nSuspendisse non fringilla nunc. Vestibulum ornare quis sem eu sollicitudin. Nam porta, eros sed aliquet varius, sapien est tempus orci, eu fermentum tortor augue in tortor. Curabitur faucibus pellentesque accumsan. Sed nec magna ut quam consectetur rutrum ac quis ante. Quisque lectus lorem, malesuada a porta non, laoreet quis urna. Aliquam lorem leo, accumsan ut bibendum eget, venenatis ac diam. Curabitur feugiat diam interdum, mattis quam quis, suscipit purus. Nunc convallis rutrum elit ac pharetra. Nunc eu tellus venenatis, dapibus mauris at, dignissim elit. Aliquam consectetur, dolor eu rhoncus tristique, mauris risus suscipit dolor, eget pharetra dolor orci id neque. Aenean vel metus ac dolor semper consectetur nec tincidunt nisi. Mauris a purus augue. Maecenas id imperdiet urna, sit amet convallis ipsum.\r\n\r\nNulla facilisi. In sed urna quis nunc finibus porta. Pellentesque euismod turpis id sollicitudin pretium. Integer ante leo, efficitur sit amet ultrices ac, pulvinar varius sapien. In vel consectetur orci. Donec eu lacus eget diam pharetra laoreet. Morbi et consequat mi. Ut ut purus non sapien interdum luctus. Pellentesque sit amet vulputate dolor. Donec in imperdiet metus, vitae commodo magna. Fusce pharetra laoreet felis eu imperdiet. Pellentesque maximus nunc accumsan elit euismod molestie. Donec id erat dictum, vestibulum velit non, placerat leo.', 'USA', '2020-12-31', '2021-01-05', 'Ted Sarno', 'ted@sarno.com', '+459 (632) 433-9307', 1),
(2, 'Tomorrowland', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisl enim, vitae placerat lorem dapibus ut. Ut lacinia ultrices convallis. Nam tristique sapien sed mollis mattis. Donec at facilisis lacus. Cras condimentum rhoncus sem lacinia congue. Nam egestas vulputate ipsum, viverra vehicula diam rutrum nec. Quisque commodo vehicula urna vel vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vehicula ex vel risus rutrum sodales. Sed consequat augue ac dui ornare, at aliquet lectus interdum. Nullam sed erat eget ex eleifend sagittis. Vestibulum tristique, neque et cursus blandit, nisi justo hendrerit diam, a condimentum dolor lacus ac elit.\r\n\r\nSuspendisse non fringilla nunc. Vestibulum ornare quis sem eu sollicitudin. Nam porta, eros sed aliquet varius, sapien est tempus orci, eu fermentum tortor augue in tortor. Curabitur faucibus pellentesque accumsan. Sed nec magna ut quam consectetur rutrum ac quis ante. Quisque lectus lorem, malesuada a porta non, laoreet quis urna. Aliquam lorem leo, accumsan ut bibendum eget, venenatis ac diam. Curabitur feugiat diam interdum, mattis quam quis, suscipit purus. Nunc convallis rutrum elit ac pharetra. Nunc eu tellus venenatis, dapibus mauris at, dignissim elit. Aliquam consectetur, dolor eu rhoncus tristique, mauris risus suscipit dolor, eget pharetra dolor orci id neque. Aenean vel metus ac dolor semper consectetur nec tincidunt nisi. Mauris a purus augue. Maecenas id imperdiet urna, sit amet convallis ipsum.\r\n\r\nNulla facilisi. In sed urna quis nunc finibus porta. Pellentesque euismod turpis id sollicitudin pretium. Integer ante leo, efficitur sit amet ultrices ac, pulvinar varius sapien. In vel consectetur orci. Donec eu lacus eget diam pharetra laoreet. Morbi et consequat mi. Ut ut purus non sapien interdum luctus. Pellentesque sit amet vulputate dolor. Donec in imperdiet metus, vitae commodo magna. Fusce pharetra laoreet felis eu imperdiet. Pellentesque maximus nunc accumsan elit euismod molestie. Donec id erat dictum, vestibulum velit non, placerat leo.', 'Belgium', '2021-10-28', '2021-11-02', 'Misha Moris', 'misha@moris.com', '+245 (442) 254-1331', 2),
(3, 'Burning Man', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisl enim, vitae placerat lorem dapibus ut. Ut lacinia ultrices convallis. Nam tristique sapien sed mollis mattis. Donec at facilisis lacus. Cras condimentum rhoncus sem lacinia congue. Nam egestas vulputate ipsum, viverra vehicula diam rutrum nec. Quisque commodo vehicula urna vel vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vehicula ex vel risus rutrum sodales. Sed consequat augue ac dui ornare, at aliquet lectus interdum. Nullam sed erat eget ex eleifend sagittis. Vestibulum tristique, neque et cursus blandit, nisi justo hendrerit diam, a condimentum dolor lacus ac elit.\r\n\r\nSuspendisse non fringilla nunc. Vestibulum ornare quis sem eu sollicitudin. Nam porta, eros sed aliquet varius, sapien est tempus orci, eu fermentum tortor augue in tortor. Curabitur faucibus pellentesque accumsan. Sed nec magna ut quam consectetur rutrum ac quis ante. Quisque lectus lorem, malesuada a porta non, laoreet quis urna. Aliquam lorem leo, accumsan ut bibendum eget, venenatis ac diam. Curabitur feugiat diam interdum, mattis quam quis, suscipit purus. Nunc convallis rutrum elit ac pharetra. Nunc eu tellus venenatis, dapibus mauris at, dignissim elit. Aliquam consectetur, dolor eu rhoncus tristique, mauris risus suscipit dolor, eget pharetra dolor orci id neque. Aenean vel metus ac dolor semper consectetur nec tincidunt nisi. Mauris a purus augue. Maecenas id imperdiet urna, sit amet convallis ipsum.\r\n\r\nNulla facilisi. In sed urna quis nunc finibus porta. Pellentesque euismod turpis id sollicitudin pretium. Integer ante leo, efficitur sit amet ultrices ac, pulvinar varius sapien. In vel consectetur orci. Donec eu lacus eget diam pharetra laoreet. Morbi et consequat mi. Ut ut purus non sapien interdum luctus. Pellentesque sit amet vulputate dolor. Donec in imperdiet metus, vitae commodo magna. Fusce pharetra laoreet felis eu imperdiet. Pellentesque maximus nunc accumsan elit euismod molestie. Donec id erat dictum, vestibulum velit non, placerat leo.', 'USA', '2021-02-21', '2021-02-23', 'Crystal Coyer', 'crystal@coyer.net', '+69 (972) 926-0230', 3),
(4, 'Rock in Rio', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisl enim, vitae placerat lorem dapibus ut. Ut lacinia ultrices convallis. Nam tristique sapien sed mollis mattis. Donec at facilisis lacus. Cras condimentum rhoncus sem lacinia congue. Nam egestas vulputate ipsum, viverra vehicula diam rutrum nec. Quisque commodo vehicula urna vel vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vehicula ex vel risus rutrum sodales. Sed consequat augue ac dui ornare, at aliquet lectus interdum. Nullam sed erat eget ex eleifend sagittis. Vestibulum tristique, neque et cursus blandit, nisi justo hendrerit diam, a condimentum dolor lacus ac elit.\r\n\r\nSuspendisse non fringilla nunc. Vestibulum ornare quis sem eu sollicitudin. Nam porta, eros sed aliquet varius, sapien est tempus orci, eu fermentum tortor augue in tortor. Curabitur faucibus pellentesque accumsan. Sed nec magna ut quam consectetur rutrum ac quis ante. Quisque lectus lorem, malesuada a porta non, laoreet quis urna. Aliquam lorem leo, accumsan ut bibendum eget, venenatis ac diam. Curabitur feugiat diam interdum, mattis quam quis, suscipit purus. Nunc convallis rutrum elit ac pharetra. Nunc eu tellus venenatis, dapibus mauris at, dignissim elit. Aliquam consectetur, dolor eu rhoncus tristique, mauris risus suscipit dolor, eget pharetra dolor orci id neque. Aenean vel metus ac dolor semper consectetur nec tincidunt nisi. Mauris a purus augue. Maecenas id imperdiet urna, sit amet convallis ipsum.\r\n\r\nNulla facilisi. In sed urna quis nunc finibus porta. Pellentesque euismod turpis id sollicitudin pretium. Integer ante leo, efficitur sit amet ultrices ac, pulvinar varius sapien. In vel consectetur orci. Donec eu lacus eget diam pharetra laoreet. Morbi et consequat mi. Ut ut purus non sapien interdum luctus. Pellentesque sit amet vulputate dolor. Donec in imperdiet metus, vitae commodo magna. Fusce pharetra laoreet felis eu imperdiet. Pellentesque maximus nunc accumsan elit euismod molestie. Donec id erat dictum, vestibulum velit non, placerat leo.', 'Brazil', '2020-04-29', '2020-05-03', 'Libby Holl', 'libby@holl.com', '+54 (827) 218-6146', 4),
(5, 'Glastonbury', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisl enim, vitae placerat lorem dapibus ut. Ut lacinia ultrices convallis. Nam tristique sapien sed mollis mattis. Donec at facilisis lacus. Cras condimentum rhoncus sem lacinia congue. Nam egestas vulputate ipsum, viverra vehicula diam rutrum nec. Quisque commodo vehicula urna vel vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vehicula ex vel risus rutrum sodales. Sed consequat augue ac dui ornare, at aliquet lectus interdum. Nullam sed erat eget ex eleifend sagittis. Vestibulum tristique, neque et cursus blandit, nisi justo hendrerit diam, a condimentum dolor lacus ac elit.\r\n\r\nSuspendisse non fringilla nunc. Vestibulum ornare quis sem eu sollicitudin. Nam porta, eros sed aliquet varius, sapien est tempus orci, eu fermentum tortor augue in tortor. Curabitur faucibus pellentesque accumsan. Sed nec magna ut quam consectetur rutrum ac quis ante. Quisque lectus lorem, malesuada a porta non, laoreet quis urna. Aliquam lorem leo, accumsan ut bibendum eget, venenatis ac diam. Curabitur feugiat diam interdum, mattis quam quis, suscipit purus. Nunc convallis rutrum elit ac pharetra. Nunc eu tellus venenatis, dapibus mauris at, dignissim elit. Aliquam consectetur, dolor eu rhoncus tristique, mauris risus suscipit dolor, eget pharetra dolor orci id neque. Aenean vel metus ac dolor semper consectetur nec tincidunt nisi. Mauris a purus augue. Maecenas id imperdiet urna, sit amet convallis ipsum.\r\n\r\nNulla facilisi. In sed urna quis nunc finibus porta. Pellentesque euismod turpis id sollicitudin pretium. Integer ante leo, efficitur sit amet ultrices ac, pulvinar varius sapien. In vel consectetur orci. Donec eu lacus eget diam pharetra laoreet. Morbi et consequat mi. Ut ut purus non sapien interdum luctus. Pellentesque sit amet vulputate dolor. Donec in imperdiet metus, vitae commodo magna. Fusce pharetra laoreet felis eu imperdiet. Pellentesque maximus nunc accumsan elit euismod molestie. Donec id erat dictum, vestibulum velit non, placerat leo.', 'UK', '2020-08-10', '2020-08-15', 'Young Chachere', 'young@chachere.edu', '+91 (995) 936-2364', 5),
(6, 'Creamfields', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisl enim, vitae placerat lorem dapibus ut. Ut lacinia ultrices convallis. Nam tristique sapien sed mollis mattis. Donec at facilisis lacus. Cras condimentum rhoncus sem lacinia congue. Nam egestas vulputate ipsum, viverra vehicula diam rutrum nec. Quisque commodo vehicula urna vel vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vehicula ex vel risus rutrum sodales. Sed consequat augue ac dui ornare, at aliquet lectus interdum. Nullam sed erat eget ex eleifend sagittis. Vestibulum tristique, neque et cursus blandit, nisi justo hendrerit diam, a condimentum dolor lacus ac elit.\r\n\r\nSuspendisse non fringilla nunc. Vestibulum ornare quis sem eu sollicitudin. Nam porta, eros sed aliquet varius, sapien est tempus orci, eu fermentum tortor augue in tortor. Curabitur faucibus pellentesque accumsan. Sed nec magna ut quam consectetur rutrum ac quis ante. Quisque lectus lorem, malesuada a porta non, laoreet quis urna. Aliquam lorem leo, accumsan ut bibendum eget, venenatis ac diam. Curabitur feugiat diam interdum, mattis quam quis, suscipit purus. Nunc convallis rutrum elit ac pharetra. Nunc eu tellus venenatis, dapibus mauris at, dignissim elit. Aliquam consectetur, dolor eu rhoncus tristique, mauris risus suscipit dolor, eget pharetra dolor orci id neque. Aenean vel metus ac dolor semper consectetur nec tincidunt nisi. Mauris a purus augue. Maecenas id imperdiet urna, sit amet convallis ipsum.\r\n\r\nNulla facilisi. In sed urna quis nunc finibus porta. Pellentesque euismod turpis id sollicitudin pretium. Integer ante leo, efficitur sit amet ultrices ac, pulvinar varius sapien. In vel consectetur orci. Donec eu lacus eget diam pharetra laoreet. Morbi et consequat mi. Ut ut purus non sapien interdum luctus. Pellentesque sit amet vulputate dolor. Donec in imperdiet metus, vitae commodo magna. Fusce pharetra laoreet felis eu imperdiet. Pellentesque maximus nunc accumsan elit euismod molestie. Donec id erat dictum, vestibulum velit non, placerat leo.', 'UK', '2021-05-12', '2021-05-15', 'Greta Harbison', 'greta@harbison.org', '+430 (791) 403-9253', 6),
(7, 'Time Warp', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisl enim, vitae placerat lorem dapibus ut. Ut lacinia ultrices convallis. Nam tristique sapien sed mollis mattis. Donec at facilisis lacus. Cras condimentum rhoncus sem lacinia congue. Nam egestas vulputate ipsum, viverra vehicula diam rutrum nec. Quisque commodo vehicula urna vel vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vehicula ex vel risus rutrum sodales. Sed consequat augue ac dui ornare, at aliquet lectus interdum. Nullam sed erat eget ex eleifend sagittis. Vestibulum tristique, neque et cursus blandit, nisi justo hendrerit diam, a condimentum dolor lacus ac elit.\r\n\r\nSuspendisse non fringilla nunc. Vestibulum ornare quis sem eu sollicitudin. Nam porta, eros sed aliquet varius, sapien est tempus orci, eu fermentum tortor augue in tortor. Curabitur faucibus pellentesque accumsan. Sed nec magna ut quam consectetur rutrum ac quis ante. Quisque lectus lorem, malesuada a porta non, laoreet quis urna. Aliquam lorem leo, accumsan ut bibendum eget, venenatis ac diam. Curabitur feugiat diam interdum, mattis quam quis, suscipit purus. Nunc convallis rutrum elit ac pharetra. Nunc eu tellus venenatis, dapibus mauris at, dignissim elit. Aliquam consectetur, dolor eu rhoncus tristique, mauris risus suscipit dolor, eget pharetra dolor orci id neque. Aenean vel metus ac dolor semper consectetur nec tincidunt nisi. Mauris a purus augue. Maecenas id imperdiet urna, sit amet convallis ipsum.\r\n\r\nNulla facilisi. In sed urna quis nunc finibus porta. Pellentesque euismod turpis id sollicitudin pretium. Integer ante leo, efficitur sit amet ultrices ac, pulvinar varius sapien. In vel consectetur orci. Donec eu lacus eget diam pharetra laoreet. Morbi et consequat mi. Ut ut purus non sapien interdum luctus. Pellentesque sit amet vulputate dolor. Donec in imperdiet metus, vitae commodo magna. Fusce pharetra laoreet felis eu imperdiet. Pellentesque maximus nunc accumsan elit euismod molestie. Donec id erat dictum, vestibulum velit non, placerat leo.', 'Germany', '2020-08-25', '2020-08-28', 'Lucinda Sykes', 'lucinda@sykes.co.uk', '+113 (574) 677-0413', 7),
(8, 'Reading Festival', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisl enim, vitae placerat lorem dapibus ut. Ut lacinia ultrices convallis. Nam tristique sapien sed mollis mattis. Donec at facilisis lacus. Cras condimentum rhoncus sem lacinia congue. Nam egestas vulputate ipsum, viverra vehicula diam rutrum nec. Quisque commodo vehicula urna vel vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vehicula ex vel risus rutrum sodales. Sed consequat augue ac dui ornare, at aliquet lectus interdum. Nullam sed erat eget ex eleifend sagittis. Vestibulum tristique, neque et cursus blandit, nisi justo hendrerit diam, a condimentum dolor lacus ac elit.\r\n\r\nSuspendisse non fringilla nunc. Vestibulum ornare quis sem eu sollicitudin. Nam porta, eros sed aliquet varius, sapien est tempus orci, eu fermentum tortor augue in tortor. Curabitur faucibus pellentesque accumsan. Sed nec magna ut quam consectetur rutrum ac quis ante. Quisque lectus lorem, malesuada a porta non, laoreet quis urna. Aliquam lorem leo, accumsan ut bibendum eget, venenatis ac diam. Curabitur feugiat diam interdum, mattis quam quis, suscipit purus. Nunc convallis rutrum elit ac pharetra. Nunc eu tellus venenatis, dapibus mauris at, dignissim elit. Aliquam consectetur, dolor eu rhoncus tristique, mauris risus suscipit dolor, eget pharetra dolor orci id neque. Aenean vel metus ac dolor semper consectetur nec tincidunt nisi. Mauris a purus augue. Maecenas id imperdiet urna, sit amet convallis ipsum.\r\n\r\nNulla facilisi. In sed urna quis nunc finibus porta. Pellentesque euismod turpis id sollicitudin pretium. Integer ante leo, efficitur sit amet ultrices ac, pulvinar varius sapien. In vel consectetur orci. Donec eu lacus eget diam pharetra laoreet. Morbi et consequat mi. Ut ut purus non sapien interdum luctus. Pellentesque sit amet vulputate dolor. Donec in imperdiet metus, vitae commodo magna. Fusce pharetra laoreet felis eu imperdiet. Pellentesque maximus nunc accumsan elit euismod molestie. Donec id erat dictum, vestibulum velit non, placerat leo.', 'UK', '2020-12-08', '2020-12-13', 'Gilma Marroquin', 'gilma@marroquin.org.uk', '+289 (653) 448-3323', 8),
(9, 'Fuji Rock', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisl enim, vitae placerat lorem dapibus ut. Ut lacinia ultrices convallis. Nam tristique sapien sed mollis mattis. Donec at facilisis lacus. Cras condimentum rhoncus sem lacinia congue. Nam egestas vulputate ipsum, viverra vehicula diam rutrum nec. Quisque commodo vehicula urna vel vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vehicula ex vel risus rutrum sodales. Sed consequat augue ac dui ornare, at aliquet lectus interdum. Nullam sed erat eget ex eleifend sagittis. Vestibulum tristique, neque et cursus blandit, nisi justo hendrerit diam, a condimentum dolor lacus ac elit.\r\n\r\nSuspendisse non fringilla nunc. Vestibulum ornare quis sem eu sollicitudin. Nam porta, eros sed aliquet varius, sapien est tempus orci, eu fermentum tortor augue in tortor. Curabitur faucibus pellentesque accumsan. Sed nec magna ut quam consectetur rutrum ac quis ante. Quisque lectus lorem, malesuada a porta non, laoreet quis urna. Aliquam lorem leo, accumsan ut bibendum eget, venenatis ac diam. Curabitur feugiat diam interdum, mattis quam quis, suscipit purus. Nunc convallis rutrum elit ac pharetra. Nunc eu tellus venenatis, dapibus mauris at, dignissim elit. Aliquam consectetur, dolor eu rhoncus tristique, mauris risus suscipit dolor, eget pharetra dolor orci id neque. Aenean vel metus ac dolor semper consectetur nec tincidunt nisi. Mauris a purus augue. Maecenas id imperdiet urna, sit amet convallis ipsum.\r\n\r\nNulla facilisi. In sed urna quis nunc finibus porta. Pellentesque euismod turpis id sollicitudin pretium. Integer ante leo, efficitur sit amet ultrices ac, pulvinar varius sapien. In vel consectetur orci. Donec eu lacus eget diam pharetra laoreet. Morbi et consequat mi. Ut ut purus non sapien interdum luctus. Pellentesque sit amet vulputate dolor. Donec in imperdiet metus, vitae commodo magna. Fusce pharetra laoreet felis eu imperdiet. Pellentesque maximus nunc accumsan elit euismod molestie. Donec id erat dictum, vestibulum velit non, placerat leo.', 'Japan', '2021-09-17', '2021-09-19', 'Dwana Marti', 'dwana@matri.ca', '+169 (375) 630-6230', 9),
(10, 'Mysteryland', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisl enim, vitae placerat lorem dapibus ut. Ut lacinia ultrices convallis. Nam tristique sapien sed mollis mattis. Donec at facilisis lacus. Cras condimentum rhoncus sem lacinia congue. Nam egestas vulputate ipsum, viverra vehicula diam rutrum nec. Quisque commodo vehicula urna vel vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vehicula ex vel risus rutrum sodales. Sed consequat augue ac dui ornare, at aliquet lectus interdum. Nullam sed erat eget ex eleifend sagittis. Vestibulum tristique, neque et cursus blandit, nisi justo hendrerit diam, a condimentum dolor lacus ac elit.\r\n\r\nSuspendisse non fringilla nunc. Vestibulum ornare quis sem eu sollicitudin. Nam porta, eros sed aliquet varius, sapien est tempus orci, eu fermentum tortor augue in tortor. Curabitur faucibus pellentesque accumsan. Sed nec magna ut quam consectetur rutrum ac quis ante. Quisque lectus lorem, malesuada a porta non, laoreet quis urna. Aliquam lorem leo, accumsan ut bibendum eget, venenatis ac diam. Curabitur feugiat diam interdum, mattis quam quis, suscipit purus. Nunc convallis rutrum elit ac pharetra. Nunc eu tellus venenatis, dapibus mauris at, dignissim elit. Aliquam consectetur, dolor eu rhoncus tristique, mauris risus suscipit dolor, eget pharetra dolor orci id neque. Aenean vel metus ac dolor semper consectetur nec tincidunt nisi. Mauris a purus augue. Maecenas id imperdiet urna, sit amet convallis ipsum.\r\n\r\nNulla facilisi. In sed urna quis nunc finibus porta. Pellentesque euismod turpis id sollicitudin pretium. Integer ante leo, efficitur sit amet ultrices ac, pulvinar varius sapien. In vel consectetur orci. Donec eu lacus eget diam pharetra laoreet. Morbi et consequat mi. Ut ut purus non sapien interdum luctus. Pellentesque sit amet vulputate dolor. Donec in imperdiet metus, vitae commodo magna. Fusce pharetra laoreet felis eu imperdiet. Pellentesque maximus nunc accumsan elit euismod molestie. Donec id erat dictum, vestibulum velit non, placerat leo.', 'Netherlands', '2020-11-14', '2020-11-16', 'Phylis Vanwart', 'phylis@vanwart.com', '+370 (931) 677-8263', 10),
(11, 'Sziget Festival', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisl enim, vitae placerat lorem dapibus ut. Ut lacinia ultrices convallis. Nam tristique sapien sed mollis mattis. Donec at facilisis lacus. Cras condimentum rhoncus sem lacinia congue. Nam egestas vulputate ipsum, viverra vehicula diam rutrum nec. Quisque commodo vehicula urna vel vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vehicula ex vel risus rutrum sodales. Sed consequat augue ac dui ornare, at aliquet lectus interdum. Nullam sed erat eget ex eleifend sagittis. Vestibulum tristique, neque et cursus blandit, nisi justo hendrerit diam, a condimentum dolor lacus ac elit.\r\n\r\nSuspendisse non fringilla nunc. Vestibulum ornare quis sem eu sollicitudin. Nam porta, eros sed aliquet varius, sapien est tempus orci, eu fermentum tortor augue in tortor. Curabitur faucibus pellentesque accumsan. Sed nec magna ut quam consectetur rutrum ac quis ante. Quisque lectus lorem, malesuada a porta non, laoreet quis urna. Aliquam lorem leo, accumsan ut bibendum eget, venenatis ac diam. Curabitur feugiat diam interdum, mattis quam quis, suscipit purus. Nunc convallis rutrum elit ac pharetra. Nunc eu tellus venenatis, dapibus mauris at, dignissim elit. Aliquam consectetur, dolor eu rhoncus tristique, mauris risus suscipit dolor, eget pharetra dolor orci id neque. Aenean vel metus ac dolor semper consectetur nec tincidunt nisi. Mauris a purus augue. Maecenas id imperdiet urna, sit amet convallis ipsum.\r\n\r\nNulla facilisi. In sed urna quis nunc finibus porta. Pellentesque euismod turpis id sollicitudin pretium. Integer ante leo, efficitur sit amet ultrices ac, pulvinar varius sapien. In vel consectetur orci. Donec eu lacus eget diam pharetra laoreet. Morbi et consequat mi. Ut ut purus non sapien interdum luctus. Pellentesque sit amet vulputate dolor. Donec in imperdiet metus, vitae commodo magna. Fusce pharetra laoreet felis eu imperdiet. Pellentesque maximus nunc accumsan elit euismod molestie. Donec id erat dictum, vestibulum velit non, placerat leo.', 'Hungary', '2021-06-03', '2021-06-07', 'Ebonie Kerfoot', 'ebonie@kerfoot.edu', '+283 (785) 655-5296', 11),
(12, 'Mawazine', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisl enim, vitae placerat lorem dapibus ut. Ut lacinia ultrices convallis. Nam tristique sapien sed mollis mattis. Donec at facilisis lacus. Cras condimentum rhoncus sem lacinia congue. Nam egestas vulputate ipsum, viverra vehicula diam rutrum nec. Quisque commodo vehicula urna vel vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vehicula ex vel risus rutrum sodales. Sed consequat augue ac dui ornare, at aliquet lectus interdum. Nullam sed erat eget ex eleifend sagittis. Vestibulum tristique, neque et cursus blandit, nisi justo hendrerit diam, a condimentum dolor lacus ac elit.\r\n\r\nSuspendisse non fringilla nunc. Vestibulum ornare quis sem eu sollicitudin. Nam porta, eros sed aliquet varius, sapien est tempus orci, eu fermentum tortor augue in tortor. Curabitur faucibus pellentesque accumsan. Sed nec magna ut quam consectetur rutrum ac quis ante. Quisque lectus lorem, malesuada a porta non, laoreet quis urna. Aliquam lorem leo, accumsan ut bibendum eget, venenatis ac diam. Curabitur feugiat diam interdum, mattis quam quis, suscipit purus. Nunc convallis rutrum elit ac pharetra. Nunc eu tellus venenatis, dapibus mauris at, dignissim elit. Aliquam consectetur, dolor eu rhoncus tristique, mauris risus suscipit dolor, eget pharetra dolor orci id neque. Aenean vel metus ac dolor semper consectetur nec tincidunt nisi. Mauris a purus augue. Maecenas id imperdiet urna, sit amet convallis ipsum.\r\n\r\nNulla facilisi. In sed urna quis nunc finibus porta. Pellentesque euismod turpis id sollicitudin pretium. Integer ante leo, efficitur sit amet ultrices ac, pulvinar varius sapien. In vel consectetur orci. Donec eu lacus eget diam pharetra laoreet. Morbi et consequat mi. Ut ut purus non sapien interdum luctus. Pellentesque sit amet vulputate dolor. Donec in imperdiet metus, vitae commodo magna. Fusce pharetra laoreet felis eu imperdiet. Pellentesque maximus nunc accumsan elit euismod molestie. Donec id erat dictum, vestibulum velit non, placerat leo.', 'Morocco', '2021-10-04', '2021-10-06', 'Hershel Wyss', 'herschel@wyss.org', '+496 (688) 451-2328', 12),
(13, 'Primavera Sound', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisl enim, vitae placerat lorem dapibus ut. Ut lacinia ultrices convallis. Nam tristique sapien sed mollis mattis. Donec at facilisis lacus. Cras condimentum rhoncus sem lacinia congue. Nam egestas vulputate ipsum, viverra vehicula diam rutrum nec. Quisque commodo vehicula urna vel vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vehicula ex vel risus rutrum sodales. Sed consequat augue ac dui ornare, at aliquet lectus interdum. Nullam sed erat eget ex eleifend sagittis. Vestibulum tristique, neque et cursus blandit, nisi justo hendrerit diam, a condimentum dolor lacus ac elit.\r\n\r\nSuspendisse non fringilla nunc. Vestibulum ornare quis sem eu sollicitudin. Nam porta, eros sed aliquet varius, sapien est tempus orci, eu fermentum tortor augue in tortor. Curabitur faucibus pellentesque accumsan. Sed nec magna ut quam consectetur rutrum ac quis ante. Quisque lectus lorem, malesuada a porta non, laoreet quis urna. Aliquam lorem leo, accumsan ut bibendum eget, venenatis ac diam. Curabitur feugiat diam interdum, mattis quam quis, suscipit purus. Nunc convallis rutrum elit ac pharetra. Nunc eu tellus venenatis, dapibus mauris at, dignissim elit. Aliquam consectetur, dolor eu rhoncus tristique, mauris risus suscipit dolor, eget pharetra dolor orci id neque. Aenean vel metus ac dolor semper consectetur nec tincidunt nisi. Mauris a purus augue. Maecenas id imperdiet urna, sit amet convallis ipsum.\r\n\r\nNulla facilisi. In sed urna quis nunc finibus porta. Pellentesque euismod turpis id sollicitudin pretium. Integer ante leo, efficitur sit amet ultrices ac, pulvinar varius sapien. In vel consectetur orci. Donec eu lacus eget diam pharetra laoreet. Morbi et consequat mi. Ut ut purus non sapien interdum luctus. Pellentesque sit amet vulputate dolor. Donec in imperdiet metus, vitae commodo magna. Fusce pharetra laoreet felis eu imperdiet. Pellentesque maximus nunc accumsan elit euismod molestie. Donec id erat dictum, vestibulum velit non, placerat leo.', 'Spain', '2021-08-15', '2021-08-18', 'Kelvin Adger', 'kelvin@adgar.edu', '+129 (922) 845-1533', 13),
(14, 'Osheaga Music and Arts Festival', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisl enim, vitae placerat lorem dapibus ut. Ut lacinia ultrices convallis. Nam tristique sapien sed mollis mattis. Donec at facilisis lacus. Cras condimentum rhoncus sem lacinia congue. Nam egestas vulputate ipsum, viverra vehicula diam rutrum nec. Quisque commodo vehicula urna vel vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vehicula ex vel risus rutrum sodales. Sed consequat augue ac dui ornare, at aliquet lectus interdum. Nullam sed erat eget ex eleifend sagittis. Vestibulum tristique, neque et cursus blandit, nisi justo hendrerit diam, a condimentum dolor lacus ac elit.\r\n\r\nSuspendisse non fringilla nunc. Vestibulum ornare quis sem eu sollicitudin. Nam porta, eros sed aliquet varius, sapien est tempus orci, eu fermentum tortor augue in tortor. Curabitur faucibus pellentesque accumsan. Sed nec magna ut quam consectetur rutrum ac quis ante. Quisque lectus lorem, malesuada a porta non, laoreet quis urna. Aliquam lorem leo, accumsan ut bibendum eget, venenatis ac diam. Curabitur feugiat diam interdum, mattis quam quis, suscipit purus. Nunc convallis rutrum elit ac pharetra. Nunc eu tellus venenatis, dapibus mauris at, dignissim elit. Aliquam consectetur, dolor eu rhoncus tristique, mauris risus suscipit dolor, eget pharetra dolor orci id neque. Aenean vel metus ac dolor semper consectetur nec tincidunt nisi. Mauris a purus augue. Maecenas id imperdiet urna, sit amet convallis ipsum.\r\n\r\nNulla facilisi. In sed urna quis nunc finibus porta. Pellentesque euismod turpis id sollicitudin pretium. Integer ante leo, efficitur sit amet ultrices ac, pulvinar varius sapien. In vel consectetur orci. Donec eu lacus eget diam pharetra laoreet. Morbi et consequat mi. Ut ut purus non sapien interdum luctus. Pellentesque sit amet vulputate dolor. Donec in imperdiet metus, vitae commodo magna. Fusce pharetra laoreet felis eu imperdiet. Pellentesque maximus nunc accumsan elit euismod molestie. Donec id erat dictum, vestibulum velit non, placerat leo.', 'Canada', '2021-07-18', '2021-07-23', 'Andrea Swarts', 'andrea@swarts.co.uk', '+18 (104) 250-4546', 14),
(15, 'Ultra Europe', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisl enim, vitae placerat lorem dapibus ut. Ut lacinia ultrices convallis. Nam tristique sapien sed mollis mattis. Donec at facilisis lacus. Cras condimentum rhoncus sem lacinia congue. Nam egestas vulputate ipsum, viverra vehicula diam rutrum nec. Quisque commodo vehicula urna vel vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vehicula ex vel risus rutrum sodales. Sed consequat augue ac dui ornare, at aliquet lectus interdum. Nullam sed erat eget ex eleifend sagittis. Vestibulum tristique, neque et cursus blandit, nisi justo hendrerit diam, a condimentum dolor lacus ac elit.\r\n\r\nSuspendisse non fringilla nunc. Vestibulum ornare quis sem eu sollicitudin. Nam porta, eros sed aliquet varius, sapien est tempus orci, eu fermentum tortor augue in tortor. Curabitur faucibus pellentesque accumsan. Sed nec magna ut quam consectetur rutrum ac quis ante. Quisque lectus lorem, malesuada a porta non, laoreet quis urna. Aliquam lorem leo, accumsan ut bibendum eget, venenatis ac diam. Curabitur feugiat diam interdum, mattis quam quis, suscipit purus. Nunc convallis rutrum elit ac pharetra. Nunc eu tellus venenatis, dapibus mauris at, dignissim elit. Aliquam consectetur, dolor eu rhoncus tristique, mauris risus suscipit dolor, eget pharetra dolor orci id neque. Aenean vel metus ac dolor semper consectetur nec tincidunt nisi. Mauris a purus augue. Maecenas id imperdiet urna, sit amet convallis ipsum.\r\n\r\nNulla facilisi. In sed urna quis nunc finibus porta. Pellentesque euismod turpis id sollicitudin pretium. Integer ante leo, efficitur sit amet ultrices ac, pulvinar varius sapien. In vel consectetur orci. Donec eu lacus eget diam pharetra laoreet. Morbi et consequat mi. Ut ut purus non sapien interdum luctus. Pellentesque sit amet vulputate dolor. Donec in imperdiet metus, vitae commodo magna. Fusce pharetra laoreet felis eu imperdiet. Pellentesque maximus nunc accumsan elit euismod molestie. Donec id erat dictum, vestibulum velit non, placerat leo.', 'Croatia', '2021-05-26', '2021-05-29', 'Brice Walk', 'brice@walk.ca', '+137 (157) 763-6699', 15),
(16, 'Wanderland Music & Art Festival', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisl enim, vitae placerat lorem dapibus ut. Ut lacinia ultrices convallis. Nam tristique sapien sed mollis mattis. Donec at facilisis lacus. Cras condimentum rhoncus sem lacinia congue. Nam egestas vulputate ipsum, viverra vehicula diam rutrum nec. Quisque commodo vehicula urna vel vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vehicula ex vel risus rutrum sodales. Sed consequat augue ac dui ornare, at aliquet lectus interdum. Nullam sed erat eget ex eleifend sagittis. Vestibulum tristique, neque et cursus blandit, nisi justo hendrerit diam, a condimentum dolor lacus ac elit.\r\n\r\nSuspendisse non fringilla nunc. Vestibulum ornare quis sem eu sollicitudin. Nam porta, eros sed aliquet varius, sapien est tempus orci, eu fermentum tortor augue in tortor. Curabitur faucibus pellentesque accumsan. Sed nec magna ut quam consectetur rutrum ac quis ante. Quisque lectus lorem, malesuada a porta non, laoreet quis urna. Aliquam lorem leo, accumsan ut bibendum eget, venenatis ac diam. Curabitur feugiat diam interdum, mattis quam quis, suscipit purus. Nunc convallis rutrum elit ac pharetra. Nunc eu tellus venenatis, dapibus mauris at, dignissim elit. Aliquam consectetur, dolor eu rhoncus tristique, mauris risus suscipit dolor, eget pharetra dolor orci id neque. Aenean vel metus ac dolor semper consectetur nec tincidunt nisi. Mauris a purus augue. Maecenas id imperdiet urna, sit amet convallis ipsum.\r\n\r\nNulla facilisi. In sed urna quis nunc finibus porta. Pellentesque euismod turpis id sollicitudin pretium. Integer ante leo, efficitur sit amet ultrices ac, pulvinar varius sapien. In vel consectetur orci. Donec eu lacus eget diam pharetra laoreet. Morbi et consequat mi. Ut ut purus non sapien interdum luctus. Pellentesque sit amet vulputate dolor. Donec in imperdiet metus, vitae commodo magna. Fusce pharetra laoreet felis eu imperdiet. Pellentesque maximus nunc accumsan elit euismod molestie. Donec id erat dictum, vestibulum velit non, placerat leo.', 'Philippines', '2021-07-01', '2021-07-14', 'Renea Ranck', 'renea@ranck.net', '+304 (965) 426-6733', 16);

-- --------------------------------------------------------

--
-- Table structure for table `images`
--

CREATE TABLE `images` (
  `id` int(11) NOT NULL,
  `filename` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `images`
--

INSERT INTO `images` (`id`, `filename`) VALUES
(1, 'assets/img/festival_01.png'),
(2, 'assets/img/festival_02.png'),
(3, 'assets/img/festival_03.png'),
(4, 'assets/img/festival_04.png'),
(5, 'assets/img/festival_05.png'),
(6, 'assets/img/festival_06.png'),
(7, 'assets/img/festival_07.png'),
(8, 'assets/img/festival_08.png'),
(9, 'assets/img/festival_09.png'),
(10, 'assets/img/festival_10.png'),
(11, 'assets/img/festival_11.png'),
(12, 'assets/img/festival_12.png'),
(13, 'assets/img/festival_13.png'),
(14, 'assets/img/festival_14.png'),
(15, 'assets/img/festival_15.png'),
(16, 'assets/img/festival_16.png');

-- --------------------------------------------------------

--
-- Indexes for dumped tables
--

--
-- Indexes for table `festivals`
--
ALTER TABLE `festivals`
  ADD PRIMARY KEY (`id`),
  ADD KEY `festivals_image_fk` (`image_id`);

--
-- Indexes for table `images`
--
ALTER TABLE `images`
  ADD PRIMARY KEY (`id`);

-- --------------------------------------------------------

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `festivals`
--
ALTER TABLE `festivals`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=17;

--
-- AUTO_INCREMENT for table `images`
--
ALTER TABLE `images`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=17;

-- --------------------------------------------------------

--
-- Constraints for dumped tables
--

--
-- Constraints for table `festivals`
--
ALTER TABLE `festivals`
  ADD CONSTRAINT `festivals_image_fk` FOREIGN KEY (`image_id`) REFERENCES `images` (`id`);

-- --------------------------------------------------------